### ISSUE TITLE
where to get secrets for .env file ?

### ISSUE THREAD

**Issue by pandaa880** [AlbertoPdRF/tisn.app#155]
I need **secrets for `.env` file** in order to run the backend and I need to start **frontend** and **backend** together. So, I am bit confused about the API Keys in `.env` file. Do I need to create those account myself and add keys from there ? Or you can provide me those keys privately ?

Thank You.

**Comment by AlbertoPdRF** [comment]
Hi @pandaa880! 👋 Thanks for submitting the issue!

For the `.env` file, you need to create accounts with the services and get your own secrets. Please note that the `JWT_SECRET` can be any string that you choose and, unless you run the client on a different port, the `BASE_CLIENT_URL` is `http://localhost:3000`. Apart from those two, the really necessary secret is the `DB_URL` one, which you can obtain by signing up on [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) using the free tier. The others only provide further functionality which is not really necessary for starters, but if you want them you can register to those services using the free tiers too.

I'll submit a PR now to try and make that part of the README more clear!
