### ISSUE TITLE
Restrict API to interact with the client only.

### ISSUE THREAD

**Issue by AlbertoPdRF** [AlbertoPdRF/tisn.app#22]
At least until it's crystal-clear that undesired actions can't be accomplished by interacting programatically with the API, its usage should be restricted to the client only.

By the way, this won't be needed while the app only has dummy data.

**Comment by jacklagare** [comment]
Hi @AlbertoPdRF, I have a solution for this. It's simple and makes use of the headers. Can I have a go at it?

**Comment by AlbertoPdRF** [comment]
Sure thing! I've just assigned the issue to you!

**Comment by jacklagare** [comment]
Thanks @AlbertoPdRF! Before I go start, I would just like to give you an overview of my plan. I don't want to start doing something that may not be an acceptable solution.

So basically what I had in mind was to create a middleware in `app.js` where it will check the headers for an existence of a client_id parameter and then if NODE_ENV is `production` and the value of the client_id parameter matches the CLIENT_ID env variable, it allows the request to proceed. Else, it returns an `HTTP 403` error.

How does that sound?

**Comment by AlbertoPdRF** [comment]
Yeah, let's first discuss this so we don't work in vain! So, your solution sounds mostly fine, but I think we can simplify it a bit. The reality is that we can't restrict the API to interact with the client only, so this will only be a small obstacle we put in the way. Thus, maybe we can just include an origin header on requests from the client and configure CORS appropriately?

**Comment by jacklagare** [comment]
Okay. CORS is a more elegant approach but not exactly simpler.

So what you have in mind is to have an array of allowed origins such as the one below?
`var allowlist = ['http://example1.com', 'http://example2.com']`

**Comment by AlbertoPdRF** [comment]
As we have the `BASE_CLIENT_URL` environment variable, couldn't we just use that to define the allowed origin?

**Comment by jacklagare** [comment]
Yes. Same thing.

**Comment by AlbertoPdRF** [comment]
Then I would proceed like that 🙂
