### ISSUE TITLE
Create a daily back up of the database.

### ISSUE THREAD

**Issue by AlbertoPdRF** [AlbertoPdRF/tisn.app#27]
Losing that information would be a total disaster!

**Comment by jacklagare** [comment]
Hi @AlbertoPdRF, is there a particular mechanism you have in mind for this? Can a cron job be used? I'm thinking of working on this if you're willing to make this part of Hacktoberfest 2020.

**Comment by AlbertoPdRF** [comment]
Hi @jacklagare, thanks for dropping by! 🙌

I had thought about setting up a cron job for this indeed! Seems like the way to go. As the back end is hosted on Heroku, and we can't persist uploads there, I think an option could be to compress the back up and email it to the team. If you have any other ideas, let's hear them! 😁

And yes, any approved/merged PR on this repo will count towards completing the Hacktoberfest 2020, so feel free to tackle not just this one but any issue! You can also join our Slack workspace (the link is in the README) and ping us if you need any help. 😊

**Comment by AlbertoPdRF** [comment]
BTW, I've just assigned the issue to you @jacklagare! :slightly_smiling_face:

**Comment by jacklagare** [comment]
@AlbertoPdRF, I've created a JS file that will take care of the database dump. However, I did not include setting-up cron or sending an email there. If you're okay with it, I think for clarity, it would be better to have that as separate issues because. What do you think?

**Comment by AlbertoPdRF** [comment]
As the script is not too big, I think we are good with one issue only. If we see that the set of changes grows huge, we can always separate later 🙂 Does that sound good?

**Comment by jacklagare** [comment]
Okay. Just want to clarify something. Should the cron job be created in Heroku or would you prefer that it be done in the API-level?

**Comment by AlbertoPdRF** [comment]
I would create the cron job on the API level, as I want to be as loosely coupled to Heroku as possible. And related to that: I think that at least we'll have to install an add-on to be able to run the `mongodump` command on Heroku, but everything that we can do programatically should be done like that.

**Comment by jacklagare** [comment]
Hi @AlbertoPdRF, I kept thinking about the `--oplog` issue and I realized the problem was that my MongoDB URI contains the specific database. This is the reason why adding the `--oplog` parameter caused an error since it only works for full dumps not specific databases. When I tried removing the database and added `--oplog` in the `mongodump` command, it worked properly.

**Comment by AlbertoPdRF** [comment]
Nice, thanks for  keeping an eye on this! How would we need to construct the `mongodump` command then? Do you want to submit a follow up PR with the changes? 😊
