### ISSUE TITLE
Populate the development database with dummy data

### ISSUE THREAD

**Issue by AlbertoPdRF** [AlbertoPdRF/tisn.app#279]
**Is your feature request related to a problem? Please describe.**

As of now, there's a script that can be used to populate the development database with interests, but it would be better if it also added users, events, etc.

**Describe the solution you'd like**

The script should be modified so it also adds users, events, etc.

**Describe alternatives you've considered**

Add users, events, etc. manually.

**Additional context**

This came up in a Slack conversation with @idiglove :slightly_smiling_face:

**Comment by Be-Like** [comment]
Currently in progress.

**Comment by AlbertoPdRF** [comment]
Assigned! :smiley:

**Comment by Be-Like** [comment]
@AlbertoPdRF Unless you want me working on something else, I can go ahead and start working on populating dummy events. Would you like me to include attendees and posts in the same PR as the events?

**Comment by AlbertoPdRF** [comment]
Working on populating the events sounds like a good next step to me!

And regarding your question, I would say that we should handle a collection population per PR, to try and keep them small and manageable. This way we'll be able to iterate faster ⚡

**Comment by AlbertoPdRF** [comment]
I was thinking that, just as we ask the developer if they want to drop dependent collections when deleting a collection, we could ask them if they want to populate collections when trying to populate dependent collections. As that sentence is a bit convoluted, here are some examples to clarify:
- If a developer tries to populate the users collection without having populated the interests one, present them a prompt asking if they want to populate the interests collection or continue without populating it.
- If a developer tries to populate the events collection without having populated the users collection, present them a prompt asking if they want to populate the users one or abort the events population one, as users are required in this case.

This reminds me that events must have at least one related interest, and I'm not sure now if we had that into account when creating the currently existing scripts, so that's something we need to check! 🕵
