### ISSUE TITLE
Revamp the `About` component

### ISSUE THREAD

**Issue by AlbertoPdRF** [AlbertoPdRF/tisn.app#303]
**Is your feature request related to a problem? Please describe.**

The `About` component only has text, which is not very visually appealing.

**Describe the solution you'd like**

I would like illustrations from [unDraw](https://undraw.co/) to be added to it, so it's more visually appealing.

**Describe alternatives you've considered**

Leave it as is.

**Additional context**

None.

**Comment by san-oop** [comment]
I can work on this

**Comment by AlbertoPdRF** [comment]
Awesome, thanks for taking this one on! I just assigned it to you, let me know if you need any help! :rocket:
