### ISSUE TITLE
Profile Date of Birth Incorrect

### ISSUE THREAD

**Issue by Be-Like** [AlbertoPdRF/tisn.app#311]
**Describe the bug**
The date of birth displayed in the UserDetails.js is off by a day. The DB stores it correctly, so it is only in how the date is displayed. (Dates are the worst to handle in JS).

As an aside, this [stackoverflow article](https://stackoverflow.com/a/31732581/11357799) provides an excellent example of all the ways JS handles dates. 

My strong recommendation would be to utilize a library such as Moment.js or date-fns to handle your dates. It will handle the localization and time zones much better. 

**To Reproduce**

1. Go to Users
2. See error

**Expected behavior**
Date to be correct. 

**Screenshots**
![image](https://user-images.githubusercontent.com/36450393/94708473-a6f06880-0312-11eb-82b1-4a08b63e3f1c.png)
![image](https://user-images.githubusercontent.com/36450393/94708630-d1422600-0312-11eb-91d1-6ab735a7a101.png)

**Comment by AlbertoPdRF** [comment]
Thank you for submitting this issue, @Be-Like! :tada:

We are actually using date-fns throughout the app, but something is clearly not working as intended in this case.

**Comment by Be-Like** [comment]
It looks like the parseISO(dateString) is the actual culprit. It looks like there are a couple of [issues opened](https://github.com/date-fns/date-fns/issues?q=is%3Aissue+is%3Aopen+parseISO) with date-fns regarding this.

**Comment by AlbertoPdRF** [comment]
I think the problem may be that we are parsing the date of birth using the user's timezone, when in this case we should just go with the date as is. For the details, [see the implementation here](https://github.com/Tisn/tisn.app/blob/master/client/src/logic/date-time.js#L27).

By the way, I just realized that this is probably the bug that @roramigator reported on #285 that we couldn't reproduce back then.

**Comment by idiglove** [comment]
I'm working on this :)

**Comment by AlbertoPdRF** [comment]
Assigned! ✔
