### ISSUE TITLE
Create Master Database Populate Command

### ISSUE THREAD

**Issue by Be-Like** [AlbertoPdRF/tisn.app#314]
**Is your feature request related to a problem? Please describe.**
Make a master file that will handle the database connection and population of all and/or specified tables.

**Describe alternatives you've considered**
Having separate scripts to run for each individual table.

**Additional context**
@AlbertoPdRF This is with regards to our conversation on the current pull request for the users db. It will be simpler to create a separate PR for this and then individual PR's for each table script.

**Comment by AlbertoPdRF** [comment]
Thanks for the issue @Be-Like! 🙂

Just to keep everyone in sync, this is related to #279.

Will you want to handle this one @Be-Like? 😄

**Comment by Be-Like** [comment]
If that is alright. I already did some research into it and have a good idea of the direction I will take.

**Comment by AlbertoPdRF** [comment]
Wonderful! I just assigned it to you! 🚀

**Comment by Be-Like** [comment]
@AlbertoPdRF, do you mind adding the "hacktoberfest" topic to the about portion of your project? That is, if you are open to having people participate during hacktoberfest. They changed their rules as of today that requires project to "opt-in" to hacktoberfest by including that topic so as to prevent projects from getting spammed.

**Comment by AlbertoPdRF** [comment]
I just did @Be-Like! 😃
