### ISSUE TITLE
Change SVGs main color dynamically

### ISSUE THREAD

**Issue by AlbertoPdRF** [AlbertoPdRF/tisn.app#315]
**Is your feature request related to a problem? Please describe.**

#309 introduced some SVGs that are used on the `About` component. To match the theme the user is using the app in, two SVGs of each type were added with different main colors.

**Describe the solution you'd like**

It would be better to just have one SVG of each type, and change its main color dynamically to match the theme the user is using the app in.

**Describe alternatives you've considered**

Leave the two SVGs of each type.

**Additional context**

None.

**Comment by san-oop** [comment]
would like to work on this @AlbertoPdRF

**Comment by AlbertoPdRF** [comment]
Awesome! I just assigned it to you 🙂
